Part 1 Development Branch
transistasis/PFMCPP_Project6 pull request #1
Opened 2021-08-05 03:56 UTC by transistasis

In this pull request:
* Completed the steps for Part 1
* Verified that there are no warnings or errors

2021-08-05 04:48 UTC, matkatmusic requested changes

2021-08-05 04:48 UTC, matkatmusic commented on main.cpp
> +    }
When you have to choose where to initialize your member variables and your choices are:
Constructor Member Initializer List
Inside the Constructor's body
Try to use the Constructor Member Initializer List.
The reason is that the member variables need to be instantiated/initialized when the class is created.
When you assign to them in the constructor body, you are potentially re-initializing them, which is a waste of resources.
Take a look at the output of this program: https://godbolt.org/z/q83YM63ze
Take note of the second instance being created and destroyed due to that constructor body assignment.
- [ ] revise, use the member initializer list to initialize your member variables

2021-08-06 02:32 UTC, transistasis commented on main.cpp
> +    }
That makes sense. Thanks for the example!

2021-08-06 06:34 UTC, matkatmusic approved these changes

2021-08-06 06:35 UTC, merged